/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface;


import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.CarInfo;
import model.Car_directory;

/**
 *
 * @author shivanginagar
 */
public class AddUberDataJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddDriverJPanel
     */
    
    private Car_directory carDir; 
    private JPanel rightPanel;
    
   
    AddUberDataJPanel(JPanel rightPanel, Car_directory carDir) {
        initComponents();
        this.rightPanel = rightPanel;
        this.carDir = carDir;
        
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        txtModelNumber = new javax.swing.JTextField();
        txtSerialNumber = new javax.swing.JTextField();
        txtColour = new javax.swing.JTextField();
        txtMaximumSeats = new javax.swing.JTextField();
        txtAvailableCity = new javax.swing.JTextField();
        txtManufacturedYear = new javax.swing.JTextField();
        CBAvailableYes = new javax.swing.JCheckBox();
        CBAvailableNo = new javax.swing.JCheckBox();
        CBMaintenanceNo = new javax.swing.JCheckBox();
        CBMaintenanceYes = new javax.swing.JCheckBox();
        BtnBack = new javax.swing.JButton();
        BtnAddUber = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Uber Driver");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("PT Serif Caption", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add Uber Driver");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("PT Serif Caption", 0, 18)); // NOI18N
        jLabel3.setText("Model Number :");

        jLabel4.setFont(new java.awt.Font("PT Serif Caption", 0, 18)); // NOI18N
        jLabel4.setText("Brand Name :");

        jLabel5.setFont(new java.awt.Font("PT Serif Caption", 0, 18)); // NOI18N
        jLabel5.setText("Serial Number :");

        jLabel6.setFont(new java.awt.Font("PT Serif Caption", 0, 18)); // NOI18N
        jLabel6.setText("Color :");

        jLabel7.setFont(new java.awt.Font("PT Serif Caption", 0, 18)); // NOI18N
        jLabel7.setText("Maximum Seats :");

        jLabel10.setFont(new java.awt.Font("PT Serif Caption", 0, 18)); // NOI18N
        jLabel10.setText("Available City :");

        jLabel20.setFont(new java.awt.Font("PT Serif Caption", 0, 18)); // NOI18N
        jLabel20.setText("Manufactured Year :");

        jLabel21.setFont(new java.awt.Font("PT Serif Caption", 0, 18)); // NOI18N
        jLabel21.setText("Is Car Available ?");

        jLabel22.setFont(new java.awt.Font("PT Serif Caption", 0, 18)); // NOI18N
        jLabel22.setText("Maintenance Certificate in place ? ");

        txtBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrandActionPerformed(evt);
            }
        });

        txtModelNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelNumberActionPerformed(evt);
            }
        });

        txtSerialNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerialNumberActionPerformed(evt);
            }
        });

        txtColour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColourActionPerformed(evt);
            }
        });

        txtMaximumSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaximumSeatsActionPerformed(evt);
            }
        });

        txtAvailableCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAvailableCityActionPerformed(evt);
            }
        });

        txtManufacturedYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManufacturedYearActionPerformed(evt);
            }
        });

        CBAvailableYes.setFont(new java.awt.Font("PT Serif Caption", 0, 13)); // NOI18N
        CBAvailableYes.setText("Yes");
        CBAvailableYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBAvailableYesActionPerformed(evt);
            }
        });

        CBAvailableNo.setFont(new java.awt.Font("PT Serif Caption", 0, 13)); // NOI18N
        CBAvailableNo.setText("No");
        CBAvailableNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBAvailableNoActionPerformed(evt);
            }
        });

        CBMaintenanceNo.setFont(new java.awt.Font("PT Serif Caption", 0, 13)); // NOI18N
        CBMaintenanceNo.setText("No");
        CBMaintenanceNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBMaintenanceNoActionPerformed(evt);
            }
        });

        CBMaintenanceYes.setFont(new java.awt.Font("PT Serif Caption", 0, 13)); // NOI18N
        CBMaintenanceYes.setText("Yes");
        CBMaintenanceYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBMaintenanceYesActionPerformed(evt);
            }
        });

        BtnBack.setFont(new java.awt.Font("PT Serif Caption", 0, 18)); // NOI18N
        BtnBack.setText("<-Home");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        BtnAddUber.setFont(new java.awt.Font("PT Serif Caption", 0, 18)); // NOI18N
        BtnAddUber.setText("Save");
        BtnAddUber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddUberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(BtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                .addGap(186, 186, 186))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel22)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CBMaintenanceYes, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBMaintenanceNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtBrand)
                    .addComponent(txtModelNumber)
                    .addComponent(txtSerialNumber)
                    .addComponent(txtColour)
                    .addComponent(txtMaximumSeats)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CBAvailableYes, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBAvailableNo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtManufacturedYear)
                    .addComponent(txtAvailableCity, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnAddUber, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(BtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBrand)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtModelNumber)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtColour)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaximumSeats)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAvailableCity, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtManufacturedYear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CBAvailableYes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBAvailableNo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBMaintenanceYes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBMaintenanceNo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnAddUber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandActionPerformed

    private void txtModelNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelNumberActionPerformed

    private void txtSerialNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerialNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerialNumberActionPerformed

    private void txtColourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColourActionPerformed

    private void txtMaximumSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaximumSeatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaximumSeatsActionPerformed

    private void txtAvailableCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAvailableCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAvailableCityActionPerformed

    private void txtManufacturedYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManufacturedYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManufacturedYearActionPerformed

    private void CBAvailableYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBAvailableYesActionPerformed
        // TODO add your handling code here:
        if(CBAvailableYes.isSelected())
        {
            CBAvailableNo.setSelected(false);
        }
    }//GEN-LAST:event_CBAvailableYesActionPerformed

    private void CBAvailableNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBAvailableNoActionPerformed
        // TODO add your handling code here:
        if(CBAvailableNo.isSelected())
        {
            CBAvailableYes.setSelected(false);
        }
    }//GEN-LAST:event_CBAvailableNoActionPerformed

    private void CBMaintenanceNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBMaintenanceNoActionPerformed
        // TODO add your handling code here:
        if(CBMaintenanceNo.isSelected())
        {
            CBMaintenanceYes.setSelected(false);
        }
    }//GEN-LAST:event_CBMaintenanceNoActionPerformed

    private void CBMaintenanceYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBMaintenanceYesActionPerformed
        // TODO add your handling code here:
        if(CBMaintenanceYes.isSelected())
        {
            CBMaintenanceNo.setSelected(false);
        }
    }//GEN-LAST:event_CBMaintenanceYesActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        // TODO add your handling code here:
        rightPanel.remove(this);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.previous(rightPanel);
    }//GEN-LAST:event_BtnBackActionPerformed

    private void BtnAddUberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddUberActionPerformed
        // TODO add your handling code here:
        CarInfo car = new CarInfo();

        String brand = txtBrand.getText();
        if ( brand == null || brand.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Brand cannot be empty");
            return;
        }
        else
        {
            car.setBrandname(brand);
        }

        String model_num = txtModelNumber.getText();
        if ( model_num == null || model_num.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Model Number cannot be empty");
            return;
        }
        else
        {
            car.setModelnum(model_num);
        }

        String colour = txtColour.getText();
        if ( colour == null || colour.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Colour cannot be empty");
            return;
        }
        else
        {
            car.setColor(colour);
        }

        String available_city = txtAvailableCity.getText();
        if ( available_city == null || available_city.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Available City cannot be empty");
            return;
        }
        else
        {
            car.setAvailablecity(available_city);
        }

        String serial_num = txtSerialNumber.getText();
        try {
            Integer.parseInt(serial_num);
        }catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null,"Serial Number is not a valid number.");
            return;
        }

        car.setSerialnum(Integer.parseInt(serial_num));

        String manufactured_year = txtManufacturedYear.getText();
        try {
            Integer.parseInt(manufactured_year);
        }catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null,"Manufactured Year is not a valid number.");
            return;
        }

        car.setManuf_year(Integer.parseInt(manufactured_year));

        String max_seats = txtMaximumSeats.getText();
        try {
            Integer.parseInt(max_seats);
        }catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null,"Maximum Seats is not a valid number.");
            return;
        }

        car.setMaxseats(Integer.parseInt(max_seats));
        car.setMinseats(1);

        if(CBAvailableYes.isSelected() == false && CBAvailableNo.isSelected() == false)
        {
            JOptionPane.showMessageDialog(null,"Select one Option in Car Available");
            return;
        }
        else
        {
            boolean available;
            if(CBAvailableYes.isSelected() == true)
            {
                available = true;
            }
            else{
                available = false;
            }
            car.setAvailablity(available);
        }

        if(CBMaintenanceYes.isSelected() == false && CBMaintenanceNo.isSelected() == false)
        {
            JOptionPane.showMessageDialog(null,"Select one Option in Maintenance Certificate");
            return;
        }
        else
        {
            boolean available;
            if(CBMaintenanceYes.isSelected() == true)
            {
                available = true;
            }
            else{
                available = false;
            }
            car.setMaintenance_record(available);
        }

        carDir.addCarInfo(car);
        JOptionPane.showMessageDialog(null,"Uber Added Successfully");
        txtBrand.setText("");
        txtModelNumber.setText("");
        txtColour.setText("");
        txtAvailableCity.setText("");
        txtSerialNumber.setText("");
        txtManufacturedYear.setText("");
        txtMaximumSeats.setText("");
        CBAvailableYes.setSelected(false);
        CBAvailableNo.setSelected(false);
        CBMaintenanceYes.setSelected(false);
        CBMaintenanceNo.setSelected(false);
    }//GEN-LAST:event_BtnAddUberActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddUber;
    private javax.swing.JButton BtnBack;
    private javax.swing.JCheckBox CBAvailableNo;
    private javax.swing.JCheckBox CBAvailableYes;
    private javax.swing.JCheckBox CBMaintenanceNo;
    private javax.swing.JCheckBox CBMaintenanceYes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAvailableCity;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtColour;
    private javax.swing.JTextField txtManufacturedYear;
    private javax.swing.JTextField txtMaximumSeats;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtSerialNumber;
    // End of variables declaration//GEN-END:variables
}
