/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface;


import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.CarInfo;
import model.Car_directory;


/**
 *
 * @author shivanginagar
 */
public class ViewUberCarDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewDetailsJPanel
     */
    private Car_directory carDir;
    private CarInfo car;
    private JPanel rightPanel;

    ViewUberCarDetailsJPanel(JPanel rightPanel, CarInfo car) {
        initComponents();
        this.rightPanel = rightPanel;
        this.car = car;
        setText();  
    }
    
    private void setText()
    {
        txtBrand.setText(car.getBrandname());
        txtModelNumber.setText(car.getModelnum());
        txtSerialNumber.setText(String.valueOf(car.getSerialnum()));
        txtColour.setText(car.getColor());
        txtMaximumSeats.setText(String.valueOf(car.getMaxseats()));
        txtAvailableCity.setText(car.getAvailablecity());
        txtManufacturedYear.setText(String.valueOf(car.getManuf_year()));
        if(car.isAvailablity() == true)
        {
            CBAvailableYes.setSelected(true);
        }
        else
        {
            CBAvailableNo.setSelected(true);
        }
        if(car.isMaintenance_record() == true)
        {
            CBMaintenanceYes.setSelected(true);
        }
        else
        {
            CBMaintenanceNo.setSelected(true);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CBAvailableYes = new javax.swing.JCheckBox();
        txtModelNumber = new javax.swing.JTextField();
        CBAvailableNo = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        txtSerialNumber = new javax.swing.JTextField();
        CBMaintenanceYes = new javax.swing.JCheckBox();
        txtColour = new javax.swing.JTextField();
        CBMaintenanceNo = new javax.swing.JCheckBox();
        txtMaximumSeats = new javax.swing.JTextField();
        BtnSave = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtAvailableCity = new javax.swing.JTextField();
        txtManufacturedYear = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BtnUpdate = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        CBAvailableYes.setText("Yes");
        CBAvailableYes.setEnabled(false);
        CBAvailableYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBAvailableYesActionPerformed(evt);
            }
        });

        txtModelNumber.setEnabled(false);
        txtModelNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelNumberActionPerformed(evt);
            }
        });

        CBAvailableNo.setText("No");
        CBAvailableNo.setEnabled(false);
        CBAvailableNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBAvailableNoActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel20.setText("Manufactured Year :");

        txtSerialNumber.setEnabled(false);
        txtSerialNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerialNumberActionPerformed(evt);
            }
        });

        CBMaintenanceYes.setText("Yes");
        CBMaintenanceYes.setEnabled(false);
        CBMaintenanceYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBMaintenanceYesActionPerformed(evt);
            }
        });

        txtColour.setEnabled(false);
        txtColour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColourActionPerformed(evt);
            }
        });

        CBMaintenanceNo.setText("No");
        CBMaintenanceNo.setEnabled(false);
        CBMaintenanceNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBMaintenanceNoActionPerformed(evt);
            }
        });

        txtMaximumSeats.setEnabled(false);
        txtMaximumSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaximumSeatsActionPerformed(evt);
            }
        });

        BtnSave.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        BtnSave.setText("Save");
        BtnSave.setEnabled(false);
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel6.setText("Color :");

        txtAvailableCity.setEnabled(false);
        txtAvailableCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAvailableCityActionPerformed(evt);
            }
        });

        txtManufacturedYear.setEnabled(false);
        txtManufacturedYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManufacturedYearActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel21.setText(" Is Car Available ?");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel2.setText("Brand Name :");

        jLabel22.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel22.setText("Is Maintenance Certificate in place? ");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel3.setText("Model Number :");

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel10.setText("Available City :");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel4.setText("Serial Number :");

        txtBrand.setEnabled(false);
        txtBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrandActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel5.setText("Maximum Seats :");

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Uber Car Details");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        BtnUpdate.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        BtnUpdate.setText(" Update ");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(BtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CBMaintenanceYes, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBMaintenanceNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtBrand)
                    .addComponent(txtModelNumber)
                    .addComponent(txtSerialNumber)
                    .addComponent(txtColour)
                    .addComponent(txtMaximumSeats)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CBAvailableYes, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBAvailableNo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtManufacturedYear)
                    .addComponent(txtAvailableCity, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBrand)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtModelNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtSerialNumber)
                        .addGap(4, 4, 4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtColour, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaximumSeats)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAvailableCity, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtManufacturedYear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CBAvailableYes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBAvailableNo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CBMaintenanceYes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CBMaintenanceNo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51))
        );

        BtnBack.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        BtnBack.setText("<- Previous Page");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(BtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(BtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CBAvailableYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBAvailableYesActionPerformed
        // TODO add your handling code here:
        if(CBAvailableYes.isSelected())
        {
            CBAvailableNo.setSelected(false);
        }
    }//GEN-LAST:event_CBAvailableYesActionPerformed

    private void txtModelNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelNumberActionPerformed

    private void CBAvailableNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBAvailableNoActionPerformed
        // TODO add your handling code here:
        if(CBAvailableNo.isSelected())
        {
            CBAvailableYes.setSelected(false);
        }
    }//GEN-LAST:event_CBAvailableNoActionPerformed

    private void txtSerialNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerialNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerialNumberActionPerformed

    private void CBMaintenanceYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBMaintenanceYesActionPerformed
        // TODO add your handling code here:
        if(CBMaintenanceYes.isSelected())
        {
            CBMaintenanceNo.setSelected(false);
        }
    }//GEN-LAST:event_CBMaintenanceYesActionPerformed

    private void txtColourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColourActionPerformed

    private void CBMaintenanceNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBMaintenanceNoActionPerformed
        // TODO add your handling code here:
        if(CBMaintenanceNo.isSelected())
        {
            CBMaintenanceYes.setSelected(false);
        }
    }//GEN-LAST:event_CBMaintenanceNoActionPerformed

    private void txtMaximumSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaximumSeatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaximumSeatsActionPerformed

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        // TODO add your handling code here:

        String colour = txtColour.getText();
        if ( colour == null || colour.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Colour cannot be empty");
            return;
        }
        else
        {
            car.setColor(colour);
        }

        String available_city = txtAvailableCity.getText();
        if ( available_city == null || available_city.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Available City cannot be empty");
            return;
        }
        else
        {
            car.setAvailablecity(available_city);
        }

        String max_seats = txtMaximumSeats.getText();
        try {
            Integer.parseInt(max_seats);
        }catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null,"Maximum Seats is not a valid number.");
            return;
        }

        car.setMaxseats(Integer.parseInt(max_seats));

        if(CBAvailableYes.isSelected() == false && CBAvailableNo.isSelected() == false)
        {
            JOptionPane.showMessageDialog(null,"Select one Option in Car Available");
            return;
        }
        else
        {
            boolean available;
            if(CBAvailableYes.isSelected() == true)
            {
                available = true;
            }
            else{
                available = false;
            }
            car.setAvailablity(available);
        }

        if(CBMaintenanceYes.isSelected() == false && CBMaintenanceNo.isSelected() == false)
        {
            JOptionPane.showMessageDialog(null,"Select one Option in Maintenance Certificate");
            return;
        }
        else
        {
            boolean available;
            if(CBMaintenanceYes.isSelected() == true)
            {
                available = true;
            }
            else{
                available = false;
            }
            car.setMaintenance_record(available);
        }

        Date now = new Date();
        car.setCreatedOn(now);

        JOptionPane.showMessageDialog(null,"Uber Updated Successfully");
        txtColour.setEnabled(false);
        txtMaximumSeats.setEnabled(false);
        txtAvailableCity.setEnabled(false);
        CBAvailableYes.setEnabled(false);
        CBAvailableNo.setEnabled(false);
        CBMaintenanceYes.setEnabled(false);
        CBMaintenanceNo.setEnabled(false);
        BtnSave.setEnabled(false);
        BtnUpdate.setEnabled(true);
    }//GEN-LAST:event_BtnSaveActionPerformed

    private void txtAvailableCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAvailableCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAvailableCityActionPerformed

    private void txtManufacturedYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManufacturedYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManufacturedYearActionPerformed

    private void txtBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        // TODO add your handling code here:
        txtColour.setEnabled(true);
        txtMaximumSeats.setEnabled(true);
        txtAvailableCity.setEnabled(true);
        CBAvailableYes.setEnabled(true);
        CBAvailableNo.setEnabled(true);
        CBMaintenanceYes.setEnabled(true);
        CBMaintenanceNo.setEnabled(true);
        BtnSave.setEnabled(true);
        BtnUpdate.setEnabled(false);
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        // TODO add your handling code here:
        rightPanel.remove(this);
        CardLayout layout = (CardLayout) rightPanel.getLayout();

        Component[] comps = rightPanel.getComponents();
        for(Component comp : comps){
            if(comp instanceof ViewUberCarDetailsJPanel){
                DisplayUberRidesJPanel manageP = (DisplayUberRidesJPanel) comp;
                manageP.populate();
            }
        }
        layout.previous(rightPanel);
    }//GEN-LAST:event_BtnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnSave;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JCheckBox CBAvailableNo;
    private javax.swing.JCheckBox CBAvailableYes;
    private javax.swing.JCheckBox CBMaintenanceNo;
    private javax.swing.JCheckBox CBMaintenanceYes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAvailableCity;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtColour;
    private javax.swing.JTextField txtManufacturedYear;
    private javax.swing.JTextField txtMaximumSeats;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtSerialNumber;
    // End of variables declaration//GEN-END:variables
}
