/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface;

import java.awt.CardLayout;
import javax.swing.JPanel;
import model.Car_directory;

/**
 *
 * @author shivanginagar
 */
public class WelcomeHomePageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form WelcomeHomePageJPanel
     */
    private Car_directory carDir; 
    private JPanel rightPanel;
    WelcomeHomePageJPanel(JPanel rightPanel, Car_directory carDir) {
        initComponents();
        this.rightPanel = rightPanel;
        this.carDir = carDir;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitlemain = new javax.swing.JLabel();
        BtnAddUberData = new javax.swing.JButton();
        BtnViewRides = new javax.swing.JButton();
        BtnsearchRides = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        lbltitlemain.setFont(new java.awt.Font("Noto Serif Myanmar", 0, 36)); // NOI18N
        lbltitlemain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitlemain.setText("Hi, Welcome to Uber Home !!");
        lbltitlemain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbltitlemain.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        BtnAddUberData.setFont(new java.awt.Font("PT Serif Caption", 0, 18)); // NOI18N
        BtnAddUberData.setText("Add Uber Data");
        BtnAddUberData.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnAddUberData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddUberDataActionPerformed(evt);
            }
        });

        BtnViewRides.setFont(new java.awt.Font("PT Serif Caption", 0, 18)); // NOI18N
        BtnViewRides.setText("Display Rides");
        BtnViewRides.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnViewRides.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewRidesActionPerformed(evt);
            }
        });

        BtnsearchRides.setFont(new java.awt.Font("PT Serif Caption", 0, 18)); // NOI18N
        BtnsearchRides.setText("Search for Rides");
        BtnsearchRides.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnsearchRides.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnsearchRidesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbltitlemain, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnAddUberData, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(BtnsearchRides, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnViewRides, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(lbltitlemain)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAddUberData, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnsearchRides, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnViewRides, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(344, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAddUberDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddUberDataActionPerformed
        // TODO add your handling code here:
        AddUberDataJPanel panel = new AddUberDataJPanel(rightPanel, carDir);
        rightPanel.add("AddUberJPanel", panel);
        CardLayout layout = (CardLayout)rightPanel.getLayout();
        layout.next(rightPanel);
    }//GEN-LAST:event_BtnAddUberDataActionPerformed

    private void BtnViewRidesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewRidesActionPerformed
        // TODO add your handling code here:
        DisplayUberRidesJPanel panel = new DisplayUberRidesJPanel(rightPanel, carDir);
        rightPanel.add("ViewUberJPanel", panel);
        CardLayout layout = (CardLayout)rightPanel.getLayout();
        layout.next(rightPanel);
    }//GEN-LAST:event_BtnViewRidesActionPerformed

    private void BtnsearchRidesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnsearchRidesActionPerformed
        // TODO add your handling code here:
        FilterPageJPanel panel = new FilterPageJPanel(rightPanel, carDir);
        rightPanel.add("FiltersJPanel", panel);
        CardLayout layout = (CardLayout)rightPanel.getLayout();
        layout.next(rightPanel);
    }//GEN-LAST:event_BtnsearchRidesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddUberData;
    private javax.swing.JButton BtnViewRides;
    private javax.swing.JButton BtnsearchRides;
    private javax.swing.JLabel lbltitlemain;
    // End of variables declaration//GEN-END:variables
}
